---
title: "RIC vs MAC Overall survival (OS) Meta Analysis"
author: "Kushal Kumar Dey"
date: "Monday, May 18, 2015"
output: html_document
---

We compare between BMT (Bone Marrow Transplant) and PBHSCT (Peripheral Blood Stem Cell Transplant) in terms of the Overall Survival (OS), which is a key indicator of the effectiveness of the treatment and is called a primary factor. 

```{r,echo=FALSE,eval=TRUE,cache=TRUE}


########################   R packages   #################################

suppressMessages(suppressWarnings(library(rmeta)))
suppressMessages(suppressWarnings(library(meta)))
suppressMessages(suppressWarnings(library(metafor)))
suppressMessages(suppressWarnings(library(plyr)))
suppressMessages(suppressWarnings(library(dplyr)))



```

The forest plot for the primary effects is as follows : 

```{r, echo=FALSE,eval=TRUE,cache=TRUE}

##################################### Primary factor comparison ##############################################

#######################################   Loading the Data  (OS) #######################################

trials_1=c("Chunfu Li 2012","J Gaziev 2008","IB Resnick 2007","A Ghavamzadeh 2008");

BMT_events_1=c(27,9,8,85)
BMT_total_1=c(30,9,8,96)
BMT_non_events_1=BMT_total_1-BMT_events_1;
PBHSCT_events_1=c(48,7,12,72);
PBHSCT_total_1=c(52,7,12,87);
PBHSCT_non_events_1=PBHSCT_total_1-PBHSCT_events_1;
weight_1=c(0.298,0.116,0.164,0.422);

data1 <- data.frame(cbind(trials_1,BMT_events_1,BMT_total_1,PBHSCT_events_1,PBHSCT_total_1),stringsAsFactors=FALSE);

res <- rma(ai=as.numeric(data1$BMT_events_1), bi=as.numeric(data1$BMT_total_1), ci=as.numeric(data1$PBHSCT_events_1), di=as.numeric(data1$PBHSCT_total_1),data=data1,
           measure="RR", method="REML");

#########################################  Loading the Data (DFS)  #########################################

trials_2=c("Chunfu Li 2012","J Gaziev 2008","IB Resnick 2007","A Ghavamzadeh 2008");

BMT_events_2=c(25,9,7,73)
BMT_total_2=c(30,9,8,96)
BMT_non_events_2=BMT_total_2-BMT_events_2;
PBHSCT_events_2=c(47,4,9,66);
PBHSCT_total_2=c(52,7,12,87);
PBHSCT_non_events_2=PBHSCT_total_2-PBHSCT_events_2;
weight_2=c(0.391,0.054,0.113,0.443);

#########################################  Loading the Data (Engraftment)  #########################################

trials_3=c("Chunfu Li 2012","J Gaziev 2008","IB Resnick 2007","A Ghavamzadeh 2008");

BMT_events_3=c(28,9,7,79)
BMT_total_3=c(30,9,8,96)
BMT_non_events_3=BMT_total_3-BMT_events_3;
PBHSCT_events_3=c(51,7,9,79);
PBHSCT_total_3=c(52,7,12,87);
PBHSCT_non_events_3=PBHSCT_total_3-PBHSCT_events_3;
weight_3=c(0.482,0.098,0.029,0.391);

###################################  Pooling the Primary Factor Data  #####################################

BMT_events =c(BMT_events_1,BMT_events_2,BMT_events_3);
BMT_non_events = c(BMT_non_events_1,BMT_non_events_2, BMT_non_events_3);
PBHSCT_events = c(PBHSCT_events_1, PBHSCT_events_2, PBHSCT_events_3);
PBHSCT_non_events = c(PBHSCT_non_events_1, PBHSCT_non_events_2, PBHSCT_non_events_3);
weight =c(weight_1,weight_2,weight_3);
labels = c(rep("OS",4),rep("DFS",4),c(rep("Engraftment",4)));

data = data.frame(cbind(rep(trials_1,3), BMT_events, BMT_non_events, PBHSCT_events, PBHSCT_non_events,weight, labels));
#print(data)

suppressMessages(attach(data))

trial_names = rep(trials_1,3);
spacings =c(rep(".",4),rep("",4),rep(" ",4));
trial_names=paste0(rep(trials_1,3),spacings);


res <- rma(ai=as.numeric(as.vector(data$BMT_events)), bi=as.numeric(as.vector(data$BMT_non_events)), ci=as.numeric(as.vector(data$PBHSCT_events)), di=as.numeric(as.vector(data$PBHSCT_non_events)),data=data,
           slab=as.character(trial_names),
           measure="RR", method="REML");

par(font=2, cex=0.75)
forest(res,annotate=T, addfit=T,addcred=T, 
       showweight=F, xlim=c(-13, 4), ylim=c(-1,27),
       at=log(c(0.25, 0.5, 0.7, 1, 1.5, 2, 4)),
        atransf=exp,main="Primary Effects Forest Plot",
       ilab=cbind(as.numeric(as.vector(data$BMT_events)),as.numeric(as.vector(data$BMT_non_events)),
                  as.numeric(as.vector(data$PBHSCT_events)),as.numeric(as.vector(data$PBHSCT_non_events)),
                  paste0(100*round(as.numeric(as.vector(data$weight)),digits=3),"%")),
       ilab.xpos=c(-10,-8,-6,-4,-2), 
       mlab="RE model for all primary effects",
       xlab="Risk Ratio",
       rows=c(3:6,12:15,20:23),
       cex=0.80);

res.1 <- rma(ai=as.numeric(as.vector(data$BMT_events)), bi=as.numeric(as.vector(data$BMT_non_events)), ci=as.numeric(as.vector(data$PBHSCT_events)), di=as.numeric(as.vector(data$PBHSCT_non_events)),data=data,
           measure="RR", subset = (as.character(data$labels)=="OS"), method="REML");

res.2 <- rma(ai=as.numeric(as.vector(data$BMT_events)), bi=as.numeric(as.vector(data$BMT_non_events)), ci=as.numeric(as.vector(data$PBHSCT_events)), di=as.numeric(as.vector(data$PBHSCT_non_events)),data=data,
           measure="RR", subset = (as.character(data$labels)=="DFS"), method="REML");

res.3 <- rma(ai=as.numeric(as.vector(data$BMT_events)), bi=as.numeric(as.vector(data$BMT_non_events)), ci=as.numeric(as.vector(data$PBHSCT_events)), di=as.numeric(as.vector(data$PBHSCT_non_events)),data=data,
           measure="RR", subset = (as.character(data$labels)=="Engraftment"), method="REML");


addpoly(res.1, row=18.5, cex=0.75, atransf=exp, mlab="RE model for OS");
addpoly(res.2, row=10.5, cex=0.75, atransf=exp, mlab="RE model for DFS");
addpoly(res.3, row=1.5, cex=0.75, atransf=exp, mlab="RE model for Engraftment");



op <-par(cex=0.75, font=4)
text(-13, c(24, 16, 7), pos=4, c("Overall Survival", "Disease Free Survival","Engraftment"), cex=0.8)

par(font=2)
text(c(-10,-8,-6,-4,-2), 26, c("Events","Non_events", "Events", "Non_events","Weight"));
text(c(-9,-5),27,c("BMT","PBHSCT"))

par(font=2,cex=0.5)
text(c(-0.5,0.5),-1.5,c("BMT","PBHSCT"))

```


The funnel plot for the primary effects is as follows 

```{r echo=FALSE, eval=TRUE}
#####################  Funnel Plot : Publication Bias ###################3

#par(mar=c(-2,-4,-1,-1))
par(mfrow=c(3,1),font=2,cex=0.75)

funnel(res.1)
title(paste0("Funnel plot for Publication Bias (OS)", paste0("\n\nBegg's test: ",round(as.numeric(ranktest(res.1)$tau),digits=2)," (p-val= ", round(ranktest(res.1)$pval,digits=3),")",": ", "Egger's test: ", round(as.numeric(regtest(res.1)$zval),digits=2), " (p-val= ", round(regtest(res.1)$pval,digits=3),")")),
cex.main = 0.75, font.main= 2, col.main= "black")


funnel(res.2)
title(paste0("Funnel plot for Publication Bias (DFS)", paste0("\n\nBegg's test: ",round(as.numeric(ranktest(res.2)$tau),digits=2)," (p-val= ", round(ranktest(res.2)$pval,digits=3),")",": ", "Egger's test: ", round(as.numeric(regtest(res.2)$zval),digits=2), " (p-val= ", round(regtest(res.2)$pval,digits=3),")")),
cex.main = 0.75, font.main= 2, col.main= "black")


funnel(res.3)
title(paste0("Funnel plot for Publication Bias (Engraftment)", paste0("\n\nBegg's test: ",round(as.numeric(ranktest(res.3)$tau),digits=2)," (p-val= ", round(ranktest(res.3)$pval,digits=3),")",": ", "Egger's test: ", round(as.numeric(regtest(res.3)$zval),digits=2), " (p-val= ", round(regtest(res.3)$pval,digits=3),")")),
cex.main = 0.75, font.main= 2, col.main= "black")


```

